### ISSUE TITLE
Any idea on when the code and pretrained models will be released?

### ISSUE THREAD

**Issue by karynaur** [raywzy/ICT#1]
Congratulations on the great paper!! I was wondering if you could give a date as to when the model and the code will be released

**Comment by cddlyf** [comment]
hi, @karynaur , thanks for your interests. We will release the code right away upon the acceptance.

**Comment by raywzy** [comment]
The codes have been released. Thanks for waiting.

**Comment by abdoelsayed2016** [comment]
@raywzy 
what about the pre-trained models?

**Comment by raywzy** [comment]
> @raywzy
> what about the pre-trained models?
> the link is redirected to https://github.com/raywzy/ICT/blob/main
> and it is nothing

Hi, the pre-trained models have been released.
