### ISSUE TITLE
not able to download ckpts due to server problem

### ISSUE THREAD

**Issue by LigZhong** [raywzy/ICT#14]
I tried several time to download the ckpts but could not make it due to server problem. Anyone encoutered this?

**Comment by LigZhong** [comment]
The downloading crashed at the end of downloading without any problem during the process.

**Comment by LinqingZhu** [comment]
> The downloading crashed at the end of downloading without any problem during the process.

I met the same problem, did you download the pretrained model successfully?

**Comment by yoyo-nb** [comment]
same problem
