### ISSUE TITLE
Pretrained Model link not working

### ISSUE THREAD

**Issue by AH289** [raywzy/ICT#20]
Hello, thank you for the great work. I tried to download the pretrained model but I get this error:

--2021-11-23 18:50:20--  https://www.dropbox.com/s/cqjgcj0serkbdxd/ckpts_ICT.zip?dl=1
Resolving www.dropbox.com (www.dropbox.com)... 162.125.3.18, 2620:100:6018:18::a27d:312
Connecting to www.dropbox.com (www.dropbox.com)|162.125.3.18|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/dl/cqjgcj0serkbdxd/ckpts_ICT.zip [following]
--2021-11-23 18:50:20--  https://www.dropbox.com/s/dl/cqjgcj0serkbdxd/ckpts_ICT.zip
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 404 Not Found
2021-11-23 18:50:20 ERROR 404: Not Found.

The link doesn't seem to work.

**Comment by raywzy** [comment]
Sorry about that. I have updated the ckpts link.

**Comment by AH289** [comment]
Thanks a lot, the link works now.
