### ISSUE TITLE
Why not end-to-end network?

### ISSUE THREAD

**Issue by Monalissaa** [raywzy/ICT#22]
Thank you for proposing this good idea of using Transformer as a priori information! 
But why not use an end-to-end network for training, is it because the effect is not good?

**Comment by raywzy** [comment]
Great question! There are two reasons I think:

1. The output of transformer contains diversity, we don't have the GT for each sampled low-resolution images.
2. The sampling process is non-differentiable.

**Comment by Monalissaa** [comment]
> 

Understood, thanks again.
