### ISSUE TITLE
About Supplemental Material

### ISSUE THREAD

**Issue by z2liudake** [raywzy/ICT#3]
Hi, your supplemental material is empty link. Can you provide it?

**Comment by raywzy** [comment]
> Hi, your supplemental material is empty link. Can you provide it?

We are now working on preparing the camera-ready version. We will update the link asap. Please stay tuned.

**Comment by raywzy** [comment]
> Hi, your supplemental material is empty link. Can you provide it?

Hi, the supple has been released~
