### ISSUE TITLE
Minimum recommended GPUs

### ISSUE THREAD

**Issue by nickk124** [raywzy/ICT#4]
Hello, what do you think is the minimum recommended GPU specs (memory etc) for good performance, both for training on a new dataset and for testing the pluralistic completion? Thanks!

**Comment by nickk124** [comment]
Let me be specific: for working with 256x256 greyscale imgs.

**Comment by raywzy** [comment]
Could you provide some statistics of your dataset? BTW, you could also scale the parameters of transformer (layers, embedding dimensions etc.) to decrease the computational cost.

**Comment by nickk124** [comment]
Hey, thanks for getting back to me!

My data are 256x256 patches sampled randomly from much larger (about 2000x3000) single-class one-channel images. At test time, I only need to do completions on the same type of patches, for the same 128x128 mask at the center on all test imgs.

**Comment by raywzy** [comment]
> Hey, thanks for getting back to me!
> 
> My data are 256x256 patches sampled randomly from much larger (about 2000x3000) single-class one-channel images. At test time, I only need to do completions on the same type of patches, for the same 128x128 mask at the center on all test imgs.

Great~ How many such 2000x3000 images do you have?

**Comment by nickk124** [comment]
Around 8000, but I will have around 90,000 total soon.

**Comment by raywzy** [comment]
> Around 8000, but I will have around 90,000 total soon.

Got it. I think the training (90,000 images) will require about 2 days using 8xV100 (32G). Of course you can also reduce the batch size to make it work well on single GPU, which will require longer training time.

**Comment by nickk124** [comment]
Excellent, this is exactly what I need. Thank you for the quick and thorough responses!
