### ISSUE TITLE
Train on own dataset

### ISSUE THREAD

**Issue by crenaudineau1** [raywzy/ICT#6]
Hello,

Congrats for your amazing works. Could you explain the dataset specification for training on own dataset ?

- Which resolution ?
- How many images ?
- Which specification to create masks ?
- Which size for the masks ?

Could you provide a little example of the dataset with few examples ?

And finally, what is the structure folder for the dataset ?

Have a good day,

**Comment by raywzy** [comment]
Hi~ Thanks for your interets.

1. Which resolution ?
    The pre-trained model is for 256x256 resolution image. You could also train the model with other resolutions through guided upsampling network. 
2. How many images ?
    It depends on the dataset and how many images you have.
3. Which specification to create masks ?
   Generally we use the mask provided by PConv (https://nv-adlr.github.io/publication/partialconv-inpainting), but we also provide the option `--random_stroke` to automatically generate the mask for training.
4. Which size for the masks ?
    The mask size should be the same with the input.

The dataset structure folder is extremely simple. Just two folders, one for the natural intact images, one for the mask images.

Hope these could help. Feel free to further raise questions~
