### ISSUE TITLE
How much RAM does inference need?

### ISSUE THREAD

**Issue by styler00dollar** [raywzy/ICT#7]
I tried to get it working in Google Colab, but it does seem that 25GB RAM is not enough and it seems to crash during the first step. How much RAM is expected?
![unknown](https://user-images.githubusercontent.com/51405565/129476322-fdae21be-36f7-489b-838f-842d57b337ea.png)

**Comment by raywzy** [comment]
Coud you please provide more information about the crash?

**Comment by styler00dollar** [comment]
I only tried to confirm if this is normal behaviour. I tried it again and I can't seem to reproduce it. The RAM usage seems to be low. I am sorry. Seems like I got it working. I forked this repo and uploaded my Colab with some minor code modifications in case you are curious.
