### ISSUE TITLE
Transformer training problem

### ISSUE THREAD

**Issue by DQiaole** [raywzy/ICT#9]
Hello,
Congrats for your nice works. 
I use a 16G GPU, but a single card can only run batch_size 3. I turned on mixed precision training, and the other settings are --n_layer 35 --n_embd 512 --n_head 8, which is the same as your model trained on Places2.
So I want to know how do you use 8 GPUs and set the batch_size to 64 to train the transformer model?

**Comment by raywzy** [comment]
What is the length of input sequence in your setting? Moreover, I train the transformer using 32G GPUs.

**Comment by DQiaole** [comment]
> What is the length of input sequence in your setting? Moreover, I train the transformer using 32G GPUs.

My length of input sequence is 32*32. In this case, it may be a problem with GPU memory; thank you for your reply!
